apiVersion: apps/v1
kind: Deployment
metadata:
  name: knorex-deployment
  labels:
    app: knorex
spec:
  replicas: 3
  selector:
    matchLabels:
      app: knorex
  template:
    metadata:
      labels:
        app: knorex
    spec:
      containers:
      - name: knorex
        image: ishita1999/devops_knorex:flask
        ports:
        - containerPort: 5000
